#!/bin/bash
# first run ./build to build the Subsonic Docker container (this file)
# then configure Subsonic by editing ./conf
# then run ./start to start Subsonic
# run ./stop to stop Subsonic

docker build -t subsonic .
