#!/bin/bash
# first run ./build to build the Subsonic Docker container
# then configure Subsonic by editing ./conf (this file) - see README.md for help
# then run ./start to start Subsonic
# run ./stop to stop Subsonic

# see README.md before changing settings below

subsonic_dir="$(pwd)"
music="$subsonic_dir/music"
playlists="$subsonic_dir/playlists"
podcasts="$subsonic_dir/podcasts"
data="$subsonic_dir/data"

mem="250"
port=4040
https_port=0
hostip=""
context_path="/"

locale="en_US.UTF-8"
tz="America/New_York"
user="subsonic"
uid="1000"

args=""
