#!/bin/bash
# first run ./build to build the Subsonic Docker container
# then configure Subsonic by editing ./conf (this file) - see README.md for help
# then run ./start to start Subsonic
# run ./stop to stop Subsonic

# see README.md before changing settings below
# configure media directories, using full path names
# rename these if you need to match a current Subsonic setup
media_folders=(music music2 videos)
music=""
music2=""
videos=""

playlists="$(pwd)/playlists"
podcasts="$(pwd)/podcasts"

# location of Subsonic database
database="$(pwd)/database"

mem="250"
port=4040
https_port=0
hostip=""
context_path="/"

locale="en_US.UTF-8"
tz="America/New_York"
user="subsonic"
uid="$UID"

args=""
