#!/bin/bash
# this script is run inside the Docker container
# you should not need to run it

set -e
if [ "$1" = "stop" ]
then
  service subsonic stop
  exit
fi

if [ "$1" != "start" ]
then
  echo "do not run this outside of the container!"
  exit 1
fi

if [ ! -f init-complete ]
then
  touch init-complete

  unlink /etc/localtime
  ln -s /usr/share/zoneinfo/"$TZ" /etc/localtime

  echo -e "\nStarting Subsonic on $(date)"
  echo -e "\ninitializing container"
  echo "setting timezone to $TZ"

  echo "setting locale to $LOCALE"
  locale-gen "$LOCALE"
  update-locale LANG="$LOCALE"

  if [ "$SUBSONIC_USER" != "root" ]
  then
    echo "creating user $SUBSONIC_USER with uid $UID"
    useradd -u $UID -U $SUBSONIC_USER
    sed -i -e "s^SUBSONIC_USER=.*^SUBSONIC_USER=$SUBSONIC_USER^g" \
      /etc/default/subsonic
  fi

  if [ "$(ls -A /var/subsonic)" = "" ]
  then
    echo -e "\ninitializing /var/subsonic"
    cp -a subsonic/. /var/subsonic/
    chown -R "$SUBSONIC_USER:" /var/subsonic
    ls -lat /var/subsonic
  else
    echo -e "\nupdating transcode files"
    cp -au subsonic/transcode/. /var/subsonic/transcode
    chown -R "$SUBSONIC_USER:" /var/subsonic/transcode
    ls -lAt /var/subsonic/transcode
  fi
  rm -r subsonic
else
  echo -e "\n\nRestarting Subsonic on $(date)"
fi

if [ "$HOSTIP" = "" ]
then
  # https://unix.stackexchange.com/a/402160/338467
  HOSTIP=$(ip route get 8.8.8.8 || echo "0.0.0.0")
  if [ "$HOSTIP" = "0.0.0.0" ]
  then
    echo -e "\nfailed to get host ip, using 0.0.0.0 - Sonos may not work"
  else
    HOSTIP=$(awk <<<$HOSTIP '{gsub(".*src",""); print $1; exit}')
  fi
fi

sed -i -e "s^SUBSONIC_ARGS=\"\(.*\)\"^SUBSONIC_ARGS=\"\1 --host=$HOSTIP $SUBSONIC_ARGS\"^g" \
  /etc/default/subsonic

echo -e "\nstarting Subsonic with args --host=$HOSTIP $SUBSONIC_ARGS"
service subsonic start
ps -ax | grep '[j]ava'
echo -e "\nSubsonic started"

# don't exit otherwise container will stop
tail -f /dev/null
