#!/bin/bash
# first run ./build to build the Subsonic Docker container
# then configure Subsonic by editing ./conf
# then run ./start to start Subsonic (this file)
# run ./stop to stop Subsonic

set -e
source ./conf

docker run -d \
  --name subsonic \
  --restart always \
  -v $music:/var/music \
  -v $playlists:/var/playlists \
  -v $podcasts:/var/music/Podcast \
  -v $config:/var/subsonic \
  --network host \
  --env PORT="$port" \
  --env HOSTIP="$hostip" \
  --env LOCALE="$locale" \
  --env TZ="$tz" \
  --env SUBSONIC_USER="$user" \
  --env UID="$uid" \
  --env SUBSONIC_ARGS="$args --port=$port --max-memory=$mem" \
  subsonic ./run start

sleep 5
docker logs subsonic
