#!/bin/bash
# first run ./build to build the Subsonic Docker container
# then configure Subsonic by editing ./conf
# then run ./start to start Subsonic
# run ./stop to stop Subsonic (this file)

echo "stopping subsonic"
docker exec subsonic ./run stop
echo "removing subsonic container"
docker container stop -t 2 subsonic >/dev/null
docker container rm subsonic >/dev/null
