#!/bin/bash
# first run ./build to build the Subsonic Docker container
# then configure Subsonic by editing ./conf
# then run ./start to start Subsonic
# run ./stop to stop Subsonic (this file)

echo "stopping Subsonic"
docker container stop subsonic >/dev/null

[ "$1" = "--noremove" ] && exit 0
echo "removing subsonic container"
docker container rm subsonic >/dev/null
echo "run ./start to restart Subsonic"
